Update the version of OctopusDeploy/install-octupus-cli-action
Particular/push-octopus-package-action pull request #56
Opened 2024-02-23 21:33 UTC by tamararivera

Updates the version of OctopusDeploy/install-octupus-cli-action from [1.2.1 to 3.1.1](https://github.com/OctopusDeploy/install-octopus-cli-action/blob/main/migration-guide.md), which needs to use the 'octopus' command instead of 'octopus'.

2024-02-27 21:21 UTC, DavidBoike requested changes

2024-02-27 21:21 UTC, DavidBoike commented on .github/workflows/ci.yml
> +          if (($contents | Measure-Object).Count -ne 7) {
So others aren't as confused as we were
```suggestion
          # Directory entry, Metadata.ps1, Octopus-generated nuspec, + 2 assets & 2 nupkg
          if (($contents | Measure-Object).Count -ne 7) {
```

2024-02-27 21:21 UTC, DavidBoike commented on .github/workflows/ci.yml
> +          if (($contents | Measure-Object).Count -ne 10) {
```suggestion
          # Same 7 previous entries + 3 new custom metadata files
          if (($contents | Measure-Object).Count -ne 10) {
```

2024-02-28 02:22 UTC, tamararivera commented on action.yml
>        uses: actions/upload-artifact@v3.1.3
Done!

2024-02-28 22:53 UTC, DavidBoike approved these changes

2024-02-28 23:00 UTC, merged